# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('coin', models.IntegerField()),
            ],
        ),
    ]
