# Generated by Django 2.1.2 on 2018-10-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181021_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cx',
            name='owner',
        ),
        migrations.AddField(
            model_name='gameuser',
            name='curCx',
            field=models.IntegerField(default=0),
        ),
    ]
