# Generated by Django 2.1.2 on 2018-10-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181021_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameuser',
            name='curCx',
        ),
        migrations.AddField(
            model_name='gameuser',
            name='curCx_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='curUnit_id',
            field=models.IntegerField(default=0),
        ),
    ]
